GuideConverterV2
OpenLiberty/quick-labs pull request #79
Opened 2020-10-29 17:37 UTC by jakub-pomykala

Uploading GuideConverterV2

2020-10-29 17:37 UTC, jakub-pomykala commented
DO NOT MERGE

2020-10-30 10:17 UTC, austin0 requested changes
Few small changes, non-functional.

2020-10-30 10:17 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +          echo "${{ github.event.inputs.guide_name }}"
```suggestion
```

Remove as replaced by "Output message" step.

2020-10-30 10:17 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +          echo "${{ github.event.inputs.guide_name }}"
```suggestion
```

Remove as replaced by "Output message" step.

2020-10-30 10:17 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +        default: 'defaulted'
```suggestion
        default: 'qa'
```

Add a more useful default.

2020-10-30 10:17 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +        default: 'not given'
```suggestion
        default: 'guide-rest-intro'
```

Add more useful default.

2020-10-30 10:17 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +          echo "${{ github.event.inputs.guide_name }}"
```suggestion
          echo "${{ github.event.inputs.guide_name }}"
          
```

Add line between jobs.

2020-10-30 10:17 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +            branch: "${{ github.event.inputs.guide_name }}/actions"
```suggestion
            branch: "${{ github.event.inputs.guide_name }}/staging"
```

Minor change to separate PR's from master/qa branches.

2020-10-30 10:17 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +            branch: "${{ github.event.inputs.guide_name }}/actions"
```suggestion
            branch: "${{ github.event.inputs.guide_name }}/master"
```

Minor change to separate PR's from master/qa branches.

2020-10-30 11:00 UTC, jakub-pomykala commented on .github/workflows/GuideConverterAction.yaml
> +            branch: "${{ github.event.inputs.guide_name }}/actions"
Done

2020-10-30 11:00 UTC, jakub-pomykala commented on .github/workflows/GuideConverterAction.yaml
> +            branch: "${{ github.event.inputs.guide_name }}/actions"
Done

2020-10-30 11:00 UTC, jakub-pomykala commented on .github/workflows/GuideConverterAction.yaml
> +          echo "${{ github.event.inputs.guide_name }}"
Done

2020-10-30 11:00 UTC, jakub-pomykala commented on .github/workflows/GuideConverterAction.yaml
> +        default: 'not given'
Done

2020-10-30 11:01 UTC, jakub-pomykala commented on .github/workflows/GuideConverterAction.yaml
> +        default: 'defaulted'
done

2020-10-30 11:01 UTC, jakub-pomykala commented on .github/workflows/GuideConverterAction.yaml
> +          echo "${{ github.event.inputs.guide_name }}"
Done

2020-10-30 11:01 UTC, jakub-pomykala commented on .github/workflows/GuideConverterAction.yaml
> +          echo "${{ github.event.inputs.guide_name }}"
Done

2020-10-30 11:05 UTC, austin0 commented on .github/workflows/GuideConverterAction.yaml
> +    name: Output message
```suggestion
    name: Make PR to Staging
```

2020-10-30 11:10 UTC, jamiecoleman92 commented
Looks good to me. Happy for this to be merged.

2020-10-30 11:22 UTC, merged